---
title: "Analysis Overview"
output: html_document
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
#loading libraries
library(tidyverse)
library(here)
library(plotly)

```

These are interactive plots. Please select an area of the plot you would like to zoom in on.

Following plots were generated using the df_MASTERTABLE dataset.

RPKM and ORF values per sample by different georegions
```{r, echo=FALSE, message=FALSE, warning=FALSE}

df <- read_tsv(here("data/df_MASTERTABLE.txt"))

geo_group <- group_by(df, GEOREGION, SAMPLE) %>% 
    summarise(rpkm = sum(RPKM), orf = sum(ORF_COUNT))
by_geo <- group_by(geo_group, GEOREGION) %>%
    summarise(samples = n(), rpkm = sum(rpkm), orf = sum(orf))

sample_geo <- mutate(by_geo,
                     rpkm_sample = rpkm /samples,
                     orf_sample = orf / samples)

plot_ly(sample_geo,
        x = sample_geo$GEOREGION,
        y= sample_geo$rpkm_sample,
        name = "RPKM Count",
        type = "bar") %>% 
    add_trace(y = sample_geo$orf_sample, name = "ORF Count") %>% 
    layout(barmode = "group")

```

The frequencies of the Level 1 pathways present 
```{r, echo=FALSE, message=FALSE, warning=FALSE}
pwy <- group_by(df, LEVEL1, LEVEL2, LEVEL3)
plot_ly(pwy, x = pwy$LEVEL1,
        type = 'histogram')

rpkmfilter <- filter(df, RPKM > 0)
filter_coastal <- filter(rpkmfilter, BIOME == "Coastal Biome")
filter_multi <- filter(rpkmfilter, BIOME == "MULTI")
filter_polar <- filter(rpkmfilter, BIOME == "Polar Biome")
filter_trades <- filter(rpkmfilter, BIOME == "Trades Biome")
filter_westerlies <- filter(rpkmfilter, BIOME == "Westerlies Biome")


p1 <- plot_ly(filter_coastal, x = ~LEVEL1, type = "histogram", name ="Coastal") %>% layout(title = "Frequency of Level 1 Pathways in the Coastal Biome")
p2 <- plot_ly(filter_polar, x = ~LEVEL1, type = "histogram", name ="Polar") %>% layout(title = "Frequency of Level 1 Pathways in the Polar Biome")
p3 <- plot_ly(filter_trades, x = ~LEVEL1, type = "histogram", name ="Trades") %>% layout(title = "Frequency of Level 1 Pathways in the Trades Biome")
p4 <- plot_ly(filter_westerlies, x = ~LEVEL1, type = "histogram", name ="Westerlies") %>% layout(title = "Frequency of Level 1 Pathways in the Westerlies Biome")

subplot(p1, p2, p3, p4, nrows = 1, shareX = TRUE, shareY = TRUE) %>% layout(title = "Frequencies of Level 1 Pathways in the 4 Biomes")

```
Level 3 pathways in all biomes
```{r, echo=FALSE, message=FALSE, warning=FALSE}

plot_ly(pwy, x = pwy$LEVEL3,
        type = 'histogram')
```


